@echo off
echo Cleaning up development documentation files...
echo.

cd C:\xampp\htdocs\dnd-labyrinth-v2

del /Q BOARD_HEIGHT_EXPANSION.md
del /Q CLEANUP_INSTRUCTIONS.md
del /Q COMBINED_TREASURE_MESSAGE_FIX.md
del /Q CONDITIONAL_MOVES_DISPLAY.md
del /Q CONTEXT_AWARE_HELP_MESSAGES.md
del /Q DRAGON_BEHAVIOR_UPDATE.md
del /Q DRAGON_IMPROVEMENTS.md
del /Q DRAGON_PATROL.md
del /Q DRAGON_PATROL_FIX.md
del /Q DRAGON_TURN_HINT_FIX.md
del /Q DRAGON_TURN_ORDER_FIX.md
del /Q FIXES_APPLIED.md
del /Q GAME_IMPROVEMENTS_JAN_28.md
del /Q GAME_OVER_FIX.md
del /Q HELP_TIPS_PERSISTENCE.md
del /Q ICON_CHANGES.md
del /Q LEGEND_SLIDE_ANIMATION.md
del /Q LEVEL_SELECTION_MENU.md
del /Q MAGICAL_PROTECTION_EFFECTS.md
del /Q MOVE_TRACKING_FIX.md
del /Q PLAYER_DRAGON_COLLISION_FIX.md
del /Q PLAY_AGAIN_LEVEL_FIX.md
del /Q PROJECT_SUMMARY.md
del /Q QUICK_REFERENCE.md
del /Q RESPAWN_AND_PATROL_FIX.md
del /Q RIGHT_SIDEBAR_LAYOUT.md
del /Q SECRET_ROOM_ICONS_UPDATE.md
del /Q SECRET_ROOM_ICON_CSS.md
del /Q SECRET_ROOM_ICON_ENHANCEMENT.md
del /Q SETUP.md
del /Q SIDEBAR_FLEX_SPACING.md
del /Q SIDEBAR_LAYOUT_ADJUSTMENTS.md
del /Q SIDEBAR_REORGANIZATION.md
del /Q SINGLE_PLAYER_FIX.md
del /Q SMOOTH_SLIDE_ANIMATION.md
del /Q SOLO_DRAGON_WAKE_RULE.md
del /Q START_HERE.md
del /Q SYMMETRIC_WALL_DISCOVERY_FIX.md
del /Q TREASURE_FOUND_CELEBRATION.md
del /Q TREASURE_HINT_IMPROVEMENTS.md
del /Q TREASURE_HINT_MARKER.md
del /Q TREASURE_HINT_OPACITY_UPDATE.md
del /Q TREASURE_ICON_CONSISTENCY_FIX.md
del /Q TREASURE_MARKER_ENHANCEMENT.md
del /Q TREASURE_PICKUP_TURN_FLOW_FIX.md
del /Q TREASURE_SPAWN_FIX.md
del /Q TWO_PLAYER_IMPROVEMENTS.md
del /Q VIEWPORT_BOARD_SIZING.md
del /Q VISUAL_ICON_IMPROVEMENTS.md
del /Q WALL_HIT_MOVE_COST.md
del /Q WARRIOR_BATTLE_SYSTEM.md
del /Q WARRIOR_INFO_LAYOUT.md
del /Q WAYSTONE_AND_TIMER_UPDATE.md
del /Q WORKING_SMOOTH_ANIMATION.md

echo.
echo ✅ Cleanup complete!
echo.
echo Files kept:
echo   - README.md
echo   - CHANGELOG.md
echo   - LICENSE
echo   - GITHUB_GUIDE.md
echo   - GITHUB_QUICKREF.md
echo   - .gitignore
echo   - .gitattributes
echo.
echo All development documentation has been deleted.
echo Everything is consolidated in CHANGELOG.md
echo.
echo You can now delete this cleanup script: cleanup.bat
echo.
pause
